
CREATE DATABASE IF NOT EXISTS qcst;

USE qcst;

CREATE TABLE IF NOT EXISTS neural_states (
    id INT AUTO_INCREMENT PRIMARY KEY,
    x FLOAT NOT NULL,
    y FLOAT NOT NULL,
    z FLOAT NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
